"""empty message

Revision ID: 923cb9b16c7f
Revises: 3d165a70534d
Create Date: 2025-08-04 00:22:22.088692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923cb9b16c7f'
down_revision = '3d165a70534d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
