"""empty message

Revision ID: ffe32a93242f
Revises: 923cb9b16c7f
Create Date: 2025-08-04 01:43:49.071188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe32a93242f'
down_revision = '923cb9b16c7f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('surveys') as batch_op:
        batch_op.add_column(sa.Column(
            'created_at', sa.DateTime(),
            nullable=False,
            server_default=sa.text('now()')
        ))
        batch_op.add_column(sa.Column(
            'updated_at', sa.DateTime(),
            nullable=False,
            server_default=sa.text('now()')
        ))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
